### ISSUE TITLE
Missing emotes

### ISSUE THREAD

**Issue by PetGirlBecky** [equirs/emotes#2]
Cannot customize Explore emote, Shattered Relic emote or Party emote.

**Comment by equirs** [comment]
"Party" was added since I first released the plugin, so I need to add that one. As for the others, I logged in to check, and I was able to add highlights/labels to them just fine, so I'm not sure what's going wrong there without more info

**Comment by PetGirlBecky** [comment]
https://gyazo.com/78f16ab9eacd3b3b581520507a5026e6 please see attached gif

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by equirs** [comment]
I see. "Explore" can't be customized because you haven't unlocked it, and I don't see a use case for highlighting emotes you can't perform. Maybe I should update the documentation so it doesn't confuse people.

The leagues emote is more complicated than I thought, because it changes depending on which leagues outfit you have, and I have a different one. I'll look into fixing that one.

**Comment by PetGirlBecky** [comment]
No probs, thanks for your help! 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by equirs** [comment]
Fixed in version 0.0.3
